### PR TITLE
Provide a getline(3) implementation for systems without it.

### LINKED ISSUE #607: getline() not available on OSX pre-10.7
# Context

* Version of iperf3:
4f3a7a5403b61f49ab277d0756e87c651a45bdfe

* Hardware:
Mac

* Operating system (and distribution, if any):
Snow Leopard (10.6) and prior

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
built with MacPorts (gcc 4.2)

# Bug Report

* Expected Behavior
successful build

* Actual Behavior
```
Undefined symbols:
  "_getline", referenced from:
      _iperf_getpass in iperf3_profile-iperf_auth.o
ld: symbol(s) not found
```

* Steps to Reproduce
N/A

* Possible Solution
Replace the missing getline() function in [src/iperf_auth.c](https://github.com/esnet/iperf/blob/master/src/iperf_auth.c) for OSX <= 10.6. This was [proposed to libgss](http://lists.gnu.org/archive/html/help-gss/2017-04/msg00001.html) and that patch can be used here as well.

### PR DESCRIPTION
**Pull request by bmah888**
The getline(3) implementation comes from NetBSD's file(1) command.
This should make compiling work on macOS pre 10.7.  Fixes #607.

### CODE REVIEW

File: src/iperf_util.c [hunk 1]
```diff
@@ -432,3 +432,86 @@ iperf_dump_fdset(FILE *fp, char *str, int nfds, fd_set *fds)
     }
     fprintf(fp, "]\n");
 }
+
+/* Compatibility version of getline(3) for systems that don't have it.. */
+#ifndef HAVE_GETLINE
```
Comment (pprindeville) [inline src/iperf_util.c]: Now you're talking... that's what I like to see!

File: src/iperf_util.c [hunk 2]
```diff
@@ -432,3 +432,86 @@ iperf_dump_fdset(FILE *fp, char *str, int nfds, fd_set *fds)
...
+ * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
+ * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
+ * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
+ * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
+ * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
+ * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
+ * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+ * POSSIBILITY OF SUCH DAMAGE.
+ */
+ssize_t
```
Comment (pprindeville) [inline src/iperf_util.c]: If this weren't poached code, I'd suggest a `static` here to not pollute the namespace, but since it is pulled from somewhere else I'd say "leave it as-is".

File: src/iperf_util.c [hunk 3]
```diff
@@ -432,3 +432,86 @@ iperf_dump_fdset(FILE *fp, char *str, int nfds, fd_set *fds)
...
+getdelim(char **buf, size_t *bufsiz, int delimiter, FILE *fp)
+{
+	char *ptr, *eptr;
+
```
Comment (pprindeville) [inline src/iperf_util.c]: Pet peeve... multiple blank lines...
